<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('error_log_items', function (Blueprint $table) {
            // 2 short fill-in-the-blank practice sentences generated by AI
            // alongside the mistake itself, targeting the SAME error
            // pattern — {"sentence": "I ___ to work.", "answer": "commute"}.
            // Optional bonus practice, never required to advance (see
            // ⚡error-log.blade.php's checkDrill()) — nullable, not every
            // mistake reliably produces a good drill.
            $table->json('drills')->nullable()->after('correction');
        });
    }

    public function down(): void
    {
        Schema::table('error_log_items', function (Blueprint $table) {
            $table->dropColumn('drills');
        });
    }
};
